CURRENT_DIR := $(CURDIR)/FWLIB
CURRENT_SRC_DIR := $(CURRENT_DIR)/src
CURRENT_INC_DIR := $(CURRENT_DIR)/inc

SRC_C_FILES += $(wildcard $(CURRENT_SRC_DIR)/*.c)
SRC_INCFILES += $(wildcard $(CURRENT_SRC_DIR)/*.h)
SRC_CXX_FILES += $(wildcard $(CURRENT_SRC_DIR)/*.cpp)
SRC_INCDIR += $(CURRENT_INC_DIR)
